-- What is the total number of customers in the database as "total_customers"?
select count(customer_id) as total_customers from customers;

-- Find the average rating of movies having running_time greater than 178 as average_rating?
select round(avg(rating), 3) as average_rating
from movies
where running_time > 178;

-- Retrieve the movie with the longest running time?
select * from movies
order by running_time desc
limit 1;

-- Calculate the total revenue generated by the cinema hall based on the cost of bookings between 4th to 12th June 2023 as total_revenue?
SELECT SUM(cost) AS total_revenue
FROM bookings
WHERE booking_date >= '2023-06-04' AND booking_date <= '2023-06-12';

-- Calculate the total duration (in minutes) of all movies combined that are of the genre Drama as total_duration?
select sum(running_time) as total_duration
from movies
where genre = 'Drama';

-- How many bookings were made on each booking date?
select booking_date, count(*) as Ticket_booked
from bookings
group by booking_date;

/*Calculate the total cost of all bookings made by each customer as total_cost and display the customer's name along with the total cost. 
	Group the results by customer_id.*/
select name, sum(cost) as total_cost
from customers c 
join bookings b on c.customer_id = b.customer_id
group by c.customer_id;

-- Calculate the total number of bookings as total_bookings made for each movie?
select title, count(distinct booking_id) as total_bookings
from movies m 
left join bookings b on m.movie_id = b.movie_id
group by m.movie_id;

-- Find the customer id and name of the customer who made the first booking in the database?
select c.customer_id, name
from customers c
join bookings b on c.customer_id = b.customer_id
order by booking_date asc
limit 1;

/*Retrieve the customer names and the number of bookings made by each customer as booking_count, sorted in descending order 
	of the booking count.*/
select name, count(booking_id) as booking_count
from customers c 
left join bookings b on c.customer_id = b.customer_id
group by c.customer_id
order by booking_count desc;

-- Retrieve the total no of seats booked for a time later than 20:00:00 as total_seats_booked?
select sum(ticket_quantity) as total_seats_booked
from bookings
where timings > '20:00:00';

-- Retrieve the details of the customer who has bought the most number of tickets?
with total_bookings as (
    select customer_id, sum(ticket_quantity) as total_quant
    from bookings
    group by customer_id
)
select c.customer_id, name, gender, email_id, age
from customers c 
join total_bookings tb on c.customer_id = tb.customer_id
order by total_quant desc
limit 1;